[package]
name = "odilia"
version = "0.0.1"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Building a better screen reader for the Linux desktop, one step at a time."
license = "gpl-3" # Not gpl-3-or-later
readme = "README.md"
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["screen-reader", "accessibility", "a11y", "tts", "linux"]
categories = ["accessibility"]
edition = "2021"
publish = false

[package.metadata.release]
# The root crate should be released
release = true
# Update the CHANGELOG
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/odilia-app/odilia/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
atspi.workspace = true
circular-queue = "^0.2.6"
evmap = "10.0.2"
eyre.workspace = true
futures = { version = "^0.3.25", default-features = false }
odilia-common = { path = "../common" }
odilia-input = { path = "../input" }
odilia-tts = { path = "../tts" }
pin-utils = "^0.1.0"
rustc-hash = { version = "^1.1.0", default-features = false }
serde_json = "1.0.89"
ssip-client.workspace = true
tokio.workspace = true
tracing-error = "^0.2.0"
tracing-log = "^0.1.3"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "parking_lot"] }
tracing-tree = "^0.2.2"
tracing.workspace = true
xdg = "2.4.1"
zbus.workspace = true

[features]

#[build-dependencies]
#clap = { version = "3.1.8", features = ["derive"] }
#clap_complete = "3.1.1"
